### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by HectorMg**
### What does this PR do?

* Adds codeclimate-test-reporter to gemfile
* Adds Travis CI, CodeClimate and Icalia Labs badges to README
* Adds gem logo to README

### CODE REVIEW

**Comment by kurenn** [comment]
Are we adding specs to this?

**Comment by HectorMg** [comment]
@kurenn probably not, but I still though it'd be a good idea to have some sort of indicator that it is as covered as it'll get

**Comment by kurenn** [comment]
I know, but there a some things to test right?

**Comment by HectorMg** [comment]
I see a couple small methods that could probably be tested, but the codeclimate test coverage reporter says its already 100% covered and there's 0.0/0.0 LOCs covered...I think it's up to you!

**Comment by kurenn** [comment]
Well, maybe just a couple of tests on this method - https://github.com/IcaliaLabs/olimpo/blob/master/lib/olimpo.rb#L21 -

Just to make sure the variables are being set, I can merge this, but make sure you include those in the next PR...

**Comment by HectorMg** [comment]
Yeah, I was planning on doing specs after the docs setup, I actually didn't really notice there was little to test until you asked. I'll work on it next!

**Pull request merged**
